app/items/__init__.py
from flask import Blueprint

bp = Blueprint("items", __name__)

from app.items import routes

app/items/routes.py
# Third party imports
from decimal import Decimal
from flask import render_template, flash, redirect, url_for
from flask_login import current_user, login_required
from sqlalchemy import func

# Local application imports
from app import db
from app.items import bp
from app.forms import ItemForm, ItemSelectForm, DeleteConfirmationForm
from app.helpers import populateItemSelectField, calculateProfit, populateItemsObject, usd
from app.models import User, Items

# Landing page for creating, editing, or deleting items
@bp.route("/items", methods=["GET"])
@login_required
def items():

    # Form that allows user to select an existing item to edit or delete
    form = ItemSelectForm()

    populateItemSelectField(form)

    return render_template("items/adjustItem.html", form=form)

# Creates a list of dictionaries used to populate a table of all items' details
@bp.route("/itemDetails", methods=["GET"])
@login_required
def itemDetails():

    items = Items.query.filter_by(username=current_user.username).all()

    # Create a list of dictionaries with specific information about each item
    items = [{"itemName": item.itemName, "quantityRemaining": item.quantity -
              sum([sale.quantity for sale in item.sales]), "quantity":item.quantity, "date":item.date.strftime('%m/%d/%Y'), "price":usd(item.price)} for item in items]

    return render_template("items/itemDetails.html", items=items)


# Create a new item or edit an existing item's details
@bp.route("/addItem", methods=["GET", "POST"])
@login_required
def addItem():

    form = ItemForm()

    if form.validate_on_submit():

        # Check if adding this item would bring total items being tracked to greater than 30
        if len(current_user.items.all()) > 30:
            flash("Error: cannot track more than 30 items.", "error")
            return redirect(url_for("items.items"))

        # The user has altered the item name.
        if form.hidden.data and not form.hidden.data == form.itemName.data:

            # Use the unmodified item name to query the database
            itemName = form.hidden.data

            # Go through all the sales for the item and update the foreign key due to name change.
            updateForeignKey = True

        else:
            itemName = form.itemName.data
            updateForeignKey = False

        item = Items.query.filter_by(user=current_user).filter_by(
            itemName=itemName).first()

        edit = True

        # User has entered an item name that is in database, but did not arrive through the editing route.
        if item and not form.hidden.data:
            flash(
                f"Item '{itemName}' is already in database.  Use editing option to adjust it.", "error")
            return redirect(url_for("items.items"))

        # Create a new Items object if the user is entering a new item
        if item is None:
            item = Items()
            edit = False

        # Capture sales for current item in case of an item name change in the next function
        if edit:
            sales = item.sales.all()

        # Update item object with new data from form.
        populateItemsObject(item, form, edit=edit)

        # The profit for each sale will be updated given the new item information from user
        if edit:
            for sale in sales:
                if updateForeignKey:
                    # Update each sale's itemName to the new itemName from form
                    sale.itemName = item.itemName
                calculateProfit(sale)

            flash(f"Item {item.itemName} updated.", "success")
        else:
            flash(f"{item.itemName} added.", "success")

        db.session.add(item)
        db.session.commit()

        return redirect(url_for("items.items"))

    return render_template("items/addItem.html", form=form, action="Edit" if form.data['hidden'] else "Add New", itemsRemaining=db.session.query(func.count(Items.itemName)).filter_by(
        username=current_user.username).scalar())

# Route which processes a user's request to edit or delete an existing item.
@bp.route("/adjustItem", methods=["POST"])
@login_required
def adjustItem():

    form = ItemSelectForm()

    populateItemSelectField(form)

    if form.validate_on_submit():

        if form.action.data == "delete":

            return render_template("items/deleteConfirmation.html", form=DeleteConfirmationForm(hidden=form.items.data))

        elif form.action.data == "edit":

            item = Items.query.filter_by(user=current_user).filter_by(
                itemName=form.items.data).first_or_404()

            # Populate an itemForm object with item data
            itemForm = ItemForm(price=Decimal(item.price),
                                quantity=item.quantity, itemName=item.itemName)

            # Store the current name of the item in a hidden field to track if the user makes changes to the itemName.
            itemForm.hidden.data = item.itemName

            itemForm.submit.label.text = form.action.data.capitalize()

            return render_template("items/addItem.html", form=itemForm, action="Edit")

    return redirect(url_for("items.items"))

# Removes an item only after the user confirms that a deletion is desired
@bp.route("/deleteItem", methods=["POST"])
@login_required
def deleteItem():

    form = DeleteConfirmationForm()

    if form.validate_on_submit():

        item = Items.query.filter_by(user=current_user).filter_by(
            itemName=form.hidden.data).first_or_404()

        # Delete all sales history for item
        for sale in item.sales.all():
            db.session.delete(sale)

        db.session.delete(item)
        db.session.commit()

        flash(f"Item {item.itemName} deleted.", "success")

    return redirect(url_for("items.items"))

app/templates/items/_addItem.html
{% extends "items/items.html" %}

{% block item_content %}
<div class="row justify-content-around">
    <div class="col-auto">

        <div class="text-center h4">{{ action }} Item</div>
        <p class="text-center">Maximum of 50 items able to be added.</p>

        <form action="/items/addItem" method="post" class="bg-light shadow p-3 my-4" novalidate>
            {{ form.hidden_tag() }}

            <div class="form-group">
                {{ form.itemName.label }}
                {{ form.itemName(class_="form-control") }}
                {% for error in form.itemName.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.price.label }}
                {{ form.price(class_="form-control") }}
                {% for error in form.price.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.quantity.label }}
                {{ form.quantity(class_="form-control") }}
                {% for error in form.quantity.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>

            <div class="text-right">
                {{ form.submit(class_="btn btn-outline-primary btn-sm") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/items/_adjustItem.html
{% extends "items/items.html" %}

{% block item_content %}

<div class="row justify-content-around my-4">
    <div class="col-auto d-flex flex-column justify-content-center">

        <a class="text-center h5" href="{{ url_for('items.addItem') }}"><i class="fas fa-plus"></i>&nbsp&nbspAdd a new item.</a>

        {% if items %}

        <p class="my-3 text-center">Choose to edit or delete an item.</p>

        {% block edit %}{% endblock %}

        <form action="/items/adjustItem" method="post" class="bg-light shadow p-3" novalidate>
            {{ form.hidden_tag() }}
            <div class="row">
                <div class="col-sm-auto">
                    <div class="form-group">
                        {% for subfield in form.action %}
                        <div class="form-check">
                            {{ subfield }}
                            {{ subfield.label.__call__(class_="form-check-label") }}
                        </div>
                        {% endfor %}
                        {% for error in form.action.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </div>
                    <div>
                        {{ form.submit(class_="btn btn-outline-primary btn-sm") }}
                    </div>
                </div>


                <div class="col-sm-auto">
                    <div class="form-group">
                        {% for subfield in form.items %}
                        <div class="form-check">
                            {{ subfield }}
                            {{ subfield.label.__call__(class_="form-check-label") }}
                        </div>
                        {% endfor %}
                        {% for error in form.items.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </div>
                    
                </div>
            </div>
        </form>
        {% endif %}
    </div>
</div>

{% endblock %}

app/templates/items/addItem.html
{% extends "base.html" %}

{% block app_content %}
<div class="row justify-content-around">
    <div class="col-auto">

        <div class="text-center h4">{{ action }} Item</div>

        {% if action == 'Add New' %}
            <p class="text-center">Maximum of 30 items able to be added; {{ 30-itemsRemaining }} items remaining.</p>
        {% endif %}

        <form action="/items/addItem" method="post" class="bg-light shadow p-3 my-4" novalidate>
            {{ form.hidden_tag() }}

            <div class="form-group">
                {{ form.itemName.label }}
                {{ form.itemName(class_="form-control") }}
                {% for error in form.itemName.errors %}
                <span style="color: red;">{{ '[' + error + ']' if error }}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.price.label }}
                {{ form.price(class_="form-control") }}
                {% for error in form.price.errors %}
                <span style="color: red;">{{ '[' + error + ']' if error }}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.quantity.label }}
                {{ form.quantity(class_="form-control") }}
                {% for error in form.quantity.errors %}
                <span style="color: red;">{{ '[' + error + ']' if error }}</span>
                {% endfor %}
            </div>

            <div class="text-right">
                <a class="mr-3 text-secondary" href="{{ url_for('items.items') }}">Cancel</a>
                {{ form.submit(class_="btn btn-outline-primary btn-sm") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/items/adjustItem.html
{% extends "base.html" %}

{% block app_content %}

<div class="row justify-content-around my-4">
    <div class="col-auto d-flex flex-column justify-content-center">

        <a class="text-center h5" href="{{ url_for('items.addItem') }}"><i class="fas fa-plus"></i>&nbsp&nbspAdd a new
            item.</a>

        {% if form.items.choices %}
        <a class="text-center text-success mt-3" href="{{ url_for('items.itemDetails') }}">View all item details and
            remaining quantities.</a>

        <p class="my-3 text-center">Choose to edit or delete an item.</p>

        <form action="/items/adjustItem" method="post" class="bg-light shadow p-3" novalidate>
            {{ form.hidden_tag() }}
            <div class="row">
                <div class="col-sm-auto">
                    <div class="form-group">
                        {% for subfield in form.action %}
                        <div class="form-check">
                            {{ subfield }}
                            {{ subfield.label.__call__(class_="form-check-label") }}
                        </div>
                        {% endfor %}
                        {% for error in form.action.errors %}
                        <span style="color: red;">{{ '[' + error + ']' if error }}</span>
                        {% endfor %}
                    </div>
                    <div>
                        {{ form.submit(class_="btn btn-outline-primary btn-sm") }}
                    </div>
                </div>

                <div class="col-sm-auto">
                    <div class="form-group">
                        {% for subfield in form.items %}
                        <div class="form-check">
                            {{ subfield }}
                            {{ subfield.label.__call__(class_="form-check-label") }}
                        </div>
                        {% endfor %}
                        {% for error in form.items.errors %}
                        <span style="color: red;">{{ '[' + error + ']' if error }}</span>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </form>

        {% endif %}

    </div>
</div>

{% endblock %}

app/templates/items/deleteConfirmation.html
{% extends "base.html" %}

{% block app_content %}
<div class="row justify-content-around">
    <div class="col-sm-6 bg-light shadow p-3 my-4">
        <p class="blockquote text-center mb-3 font-weight-bold">Are you sure you want to delete {{ form.hidden.data }}?
        </p>
        <p class="blockquote text-center">
            This is a permanent change. Every sale in history for {{ form.hidden.data }} will be removed as well.
            All profit calculations will be adjusted accordingly.</p>

        <form action="/items/deleteItem" method="post" novalidate>
            {{ form.hidden_tag() }}

            <div class="text-right mt-sm-4">
                <a class="mr-3 text-secondary" href="{{ url_for('items.items') }}">Cancel</a>
                {{ form.confirm(class_="btn btn-danger") }}
            </div>

        </form>
    </div>
</div>
{% endblock %}

app/templates/items/itemDetails.html
{% extends "base.html" %}

{% block app_content %}

{% if items %}
<div class="row justify-content-around">
    <div class="col-auto">

        <p class="my-4 text-center h4">{{ current_user.username }}'s items for sale:</p>

        <table class="table table-hover text-center">
            <thead>
                <tr>
                    <th scope="col">Item</th>
                    <th scope="col">Quantity Remaining</th>
                    <th scope="col">Original Quantity</th>
                    <th scope="col">Date Added</th>
                    <th scope="col">Price</th>
                </tr>
            </thead>
            <tbody>
                {% for item in items %}

                {% if item.quantityRemaining <= 5 and item.quantityRemaining > 0 %}
                <tr class="alert-warning">
                {% elif item.quantityRemaining == 0 %}
                <tr class="alert-danger">
                {% else %}
                <tr>
                {% endif %}
                    <th scope="row">{{ item.itemName }}</th>
                    <td>{{ item.quantityRemaining }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.date }}</td>
                    <td>{{ item.price }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endif %}
{% endblock %}