app/main/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__)

from app.main import routes

app/main/routes.py
# Third party imports
from decimal import Decimal
from flask import render_template, flash, redirect, url_for
from flask_login import current_user, login_required
from sqlalchemy import func

# Local application imports
from app import db
from app.main import bp
from app.forms import FeeForm
from app.helpers import usd
from app.models import Sales, Items

# Dashboard of user sales
@bp.route('/')
@bp.route('/index')
@login_required
def index():

    totalNumberOfSales = Sales.query.filter_by(
        username=current_user.username).count()
    totalProfit = db.session.query(func.sum(Sales.profit)).filter_by(
        username=current_user.username).scalar()

    totalProfit = 0 if totalProfit == None else totalProfit

    items = Items.query.filter_by(user=current_user).all()

    totalSalesMessage = f"{current_user.username} is tracking {totalNumberOfSales} {'sale' if totalNumberOfSales == 1 else 'sales'} with total {'profit' if totalProfit >= 0 else 'loss'} of {usd(totalProfit or 0)}."

    return render_template("main/index.html", totalSalesMessage=totalSalesMessage)


@bp.route("/fees", methods=["GET", "POST"])
@login_required
def fees():

    form = FeeForm()

    if form.validate_on_submit():

        current_user.eBayPercent = str(form.eBayPercent.data)
        current_user.payPalPercent = str(form.payPalPercent.data)
        current_user.payPalFixed = str(form.payPalFixed.data)
        db.session.add(current_user)
        db.session.commit()
        flash("Selling fees sucessfully updated.", "success")
        return redirect(url_for("main.index"))

    form.eBayPercent.data = Decimal(current_user.eBayPercent)
    form.payPalPercent.data = Decimal(current_user.payPalPercent)
    form.payPalFixed.data = Decimal(current_user.payPalFixed)

    return render_template("main/fees.html", form=form)

app/templates/main/fees.html
{% extends "base.html" %}

{% block app_content %}
<div class="row justify-content-around">
    <div class="col-auto">

        <form action="{{ url_for('main.fees') }}" method="post" class="bg-light shadow p-3 my-4" novalidate>
            {{ form.hidden_tag() }}

            <div class="form-group">
                {{ form.eBayPercent.label }}<br>
                {{ form.eBayPercent(class_="form-control") }}
                {% for error in form.eBayPercent.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.payPalFixed.label }}<br>
                {{ form.payPalFixed(class_="form-control") }}
                {% for error in form.payPalFixed.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.payPalPercent.label }}<br>
                {{ form.payPalPercent(class_="form-control") }}
                {% for error in form.payPalPercent.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>

            <div class="text-right">
                <a class="mr-3 text-secondary" href="{{ url_for('main.index') }}">Cancel</a>
                {{ form.submit(class_="btn btn-outline-primary btn-sm") }}
            </div>

        </form>
    </div>
</div>
{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}

{% block app_content %}

<div class="row justify-content-around">
  <div class="col-auto">
    <p class="text-center h3 mt-3"><em>eBaySalt</em> <small class="text-muted">The eBay Sales Tracker</small></p>
  </div>
</div>

<div class="row justify-content-around">
  <div class="col-auto">

    <p class="text-center h5 my-5">{{totalSalesMessage}}</p>

    <ul class="list-group my-sm-4 shadow">
      <li class="list-group-item"><a class="text-dark" href="{{ url_for('sales.newSale') }}">Add a new sale.</a></li>
      <li class="list-group-item"><a class="text-dark" href="{{ url_for('sales.sales') }}">Edit or view a history of
          sales.</a></li>
      <li class="list-group-item"><a class="text-dark" href="{{ url_for('items.addItem') }}">Add a new item for
          sale.</a></li>
      <li class="list-group-item"><a class="text-dark" href="{{ url_for('main.fees') }}">Adjust selling fees.</a></li>
    </ul>

  </div>
</div>

{% endblock %}