app/sales/__init__.py
from flask import Blueprint

bp = Blueprint("sales", __name__)

from app.sales import routes

app/sales/routes.py
# Standard library imports
import ast

# Third party imports
from datetime import date
from decimal import Decimal
from flask import render_template, flash, redirect, url_for, request
from flask_login import current_user, login_required

# Local application imports
from app import db
from app.sales import bp
from app.forms import SaleForm, SaleHistoryAdjustForm
from app.helpers import populateItemSelectField, calculateProfit, populateFeeFields, createSaleActionForm, usd
from app.models import User, Sales, Items
from app.sales.createCSV import createCSV


# User can choose to view a history of sales or edit/delete/refund a sale.
@bp.route("/sales", methods=["GET", "POST"])
@login_required
def sales():

    form = createSaleActionForm()

    if form.validate_on_submit():

        # Store which items the user wants to view sales from, and the action.
        current_user.saleDisplayInfo = f"{{'userAction':'{form.action.data}', 'itemsList':{form.items.data}}}"

        db.session.add(current_user)
        db.session.commit()

        return redirect(url_for("sales.displaySales", page=1))

    zeroSales = True if not Sales.query.filter_by(
        username=current_user.username).first() else False

    zeroItems = True if not current_user.items.first() else False

    return render_template("sales/sales.html", form=form, zeroSales=zeroSales, zeroItems=zeroItems)

# Display sales to view or adjust and divided by pagination
@bp.route("/displaySales", methods=["GET"])
@login_required
def displaySales():

    page = int(request.args.get("page"))

    # Convert data with userAction and list of items into a dict
    try:
        items = ast.literal_eval(current_user.saleDisplayInfo)
    except:
        flash("Error: User must have a saleDisplayInfo dict stored.", "error")
        return redirect(url_for("sales.sales"))

    if page and items:

        # createSaleHistory returns a dictionary  {"saleHistoryQuery": saleHistoryQuery object, "saleHistoryList": list of tuples (id, dict of Sales information)}
        saleHistory = createSaleHistoryList(
            page, items["itemsList"], items["userAction"])

        # No sales are able to be edited, refunded, or deleted
        if not saleHistory["saleHistoryList"]:

            userAction = items['userAction']+'ed' if not items['userAction'][-1:] == 'e' else items['userAction']+'d'
            userAction = "viewed" if items["userAction"] == "history" else userAction

            flash(f"None of the selected items have sales that can be {userAction} yet.", "error")
            return redirect(url_for("sales.sales"))

        next_url = url_for(
            'sales.displaySales', page=saleHistory["saleHistoryQuery"].next_num) if saleHistory["saleHistoryQuery"].has_next else None
        prev_url = url_for(
            'sales.displaySales', page=saleHistory["saleHistoryQuery"].prev_num) if saleHistory["saleHistoryQuery"].has_prev else None

        if items["userAction"] in ["edit", "delete", "refund"]:
            # hidden is used to track which page of sales data is being displayed to the user
            adjustSaleHistoryForm = SaleHistoryAdjustForm(hidden=page)

            adjustSaleHistoryForm.sale.choices = saleHistory["saleHistoryList"]
            adjustSaleHistoryForm.submit.label.text = f"{items['userAction'].capitalize()} Sale"

            return render_template("sales/_saleEdit.html", userAction=items["userAction"], adjustForm=adjustSaleHistoryForm, form=createSaleActionForm(), next_url=next_url, prev_url=prev_url)
        else:

            # history will be a list of dictionaries with sale information
            history = [sale[1] for sale in saleHistory["saleHistoryList"]]

            return render_template("sales/_saleHistory.html", userAction=items["userAction"], history=history, form=createSaleActionForm(), next_url=next_url, prev_url=prev_url)

    return redirect(url_for("sales.sales"))


# Returns a dict that includes a list of sale information divided by page
def createSaleHistoryList(page, listOfItemNames, userAction=False):

    historyQuery = Sales.query.filter(
        Sales.username == current_user.username, Sales.itemName.in_(listOfItemNames)).order_by(Sales.date.desc()).paginate(page, 30, False)

    historyList = historyQuery.items

    # Remove any already refunded sales if userAction is editing or refunding
    if userAction in ["edit", "refund"]:
        historyList = [sale for sale in historyList if not sale.refund]

    for index, sale in enumerate(historyList):

        historyList[index] = (str(sale.id), {"itemName": sale.itemName, "date": sale.date.strftime('%m/%d/%Y'), "price": usd(sale.price), "priceWithTax": usd(
            sale.priceWithTax), "quantity": sale.quantity, "shipping": usd(sale.shipping), "profit": usd(sale.profit), "packaging": usd(sale.packaging), "refund": sale.refund})

    return {"saleHistoryQuery": historyQuery, "saleHistoryList": historyList}


# Enter a new sale or edit an existing one
@bp.route("/newSale", methods=["GET", "POST"])
@login_required
def newSale():

    # Redirect user to addItem if no items have been added yet.
    if not Items.query.filter_by(user=current_user).first():
        flash("Please add an item before adding a new sale.", "error")
        return redirect(url_for("items.addItem"))

    form = SaleForm()

    populateItemSelectField(form)

    if form.validate_on_submit():

        # If the id hidden field has data, the sale is being edited.
        if form.hidden.data:

            # Create a dictionary from form hidden data.
            hiddenData = ast.literal_eval(form.hidden.data)

            # Get sale from database.
            usersSale = Sales.query.filter_by(username=current_user.username).filter_by(
                id=hiddenData["id"]).first_or_404()

            flash(
                f"{form.items.data}'s sale on {form.date.raw_data[0]} has been edited.", "success")
        else:
            flash(f"New Sale Logged for {form.items.data}.", "success")
            # Create a new instance of the Sales model.
            usersSale = Sales()
            usersSale.username = current_user.username

        # Link userSale object to an Item object if there is not one linked or user changed item during edit
        if not form.hidden.data or not hiddenData["originalItemName"] == form.items.data:

            usersSale.item = Items.query.filter_by(
                user=current_user).filter_by(itemName=form.items.data).first_or_404()

        usersSale.date = form.date.data
        usersSale.price = str(form.price.data)
        usersSale.priceWithTax = str(
            form.priceWithTax.data) if form.priceWithTax.data else ""
        usersSale.quantity = form.quantity.data
        usersSale.shipping = str(form.shipping.data)
        usersSale.packaging = str(form.packaging.data)
        # eBay fees never include sales taxes
        usersSale.eBayFees = str(
            Decimal(form.price.data*form.eBayPercent.data).quantize(Decimal("1.00")))
        # PayPal fees include sales taxes
        usersSale.payPalFees = str(Decimal(
            (Decimal(form.priceWithTax.data) if form.priceWithTax.data else form.price.data) * form.payPalPercent.data + form.payPalFixed.data).quantize(Decimal("1.00")))

        calculateProfit(usersSale)

        db.session.add(usersSale)
        db.session.commit()

        return redirect(url_for("sales.sales"))

    else:
        # Prefill certain fields of the form
        form.date.data = date.today()
        populateFeeFields(form)
        return render_template("sales/saleInput.html", form=form, action="add")

# User has selected a specific sale to refund, delete, or edit
@bp.route("/adjustSaleHistory", methods=["POST"])
@login_required
def adjustSaleHistory():

    form = SaleHistoryAdjustForm()

    # requestItemsList is a dict containing userAction and itemsList
    try:
        requestItemsList = ast.literal_eval(current_user.saleDisplayInfo)
    except:
        flash("Error: User must have a saleDisplayInfo dict stored.", "error")
        return redirect(url_for("sales.sales"))

    if requestItemsList:

        # Populate sale choices to pass validation
        form.sale.choices = createSaleHistoryList(int(
            form.hidden.data), requestItemsList["itemsList"], requestItemsList["userAction"])["saleHistoryList"]

        if form.validate_on_submit():

            saleToAdjust = Sales.query.filter_by(username=current_user.username).filter_by(
                id=int(form.sale.data)).first_or_404()

            if requestItemsList["userAction"] == "delete":

                flash(
                    f"A sale from {saleToAdjust.itemName} made on {saleToAdjust.date.strftime('%m/%d/%Y')} has been deleted.", "success")

                db.session.delete(saleToAdjust)
                db.session.commit()

            elif requestItemsList["userAction"] == "edit":

                # Create a SaleForm that will be prepopulated
                saleFormToEdit = SaleForm()

                populateItemSelectField(saleFormToEdit)
                saleFormToEdit.items.data = saleToAdjust.item.itemName

                # Store a dictionary with information used to process an edit on the newSale route
                saleFormToEdit.hidden.data = {
                    "id": saleToAdjust.id, "originalItemName": saleToAdjust.item.itemName}

                saleFormToEdit.date.data = saleToAdjust.date
                saleFormToEdit.price.data = Decimal(saleToAdjust.price)
                saleFormToEdit.priceWithTax.data = Decimal(
                    saleToAdjust.priceWithTax)
                saleFormToEdit.quantity.data = saleToAdjust.quantity
                saleFormToEdit.shipping.data = Decimal(saleToAdjust.shipping)
                saleFormToEdit.packaging.data = Decimal(saleToAdjust.packaging)
                populateFeeFields(saleFormToEdit)

                return render_template("sales/saleInput.html", form=saleFormToEdit, action="edit")

app/templates/sales/_saleEdit.html
{% extends "sales/sales.html" %}

{% block history %}

{% if adjustForm %}
<div class="row justify-content-around">
    <div class="col-auto">
        
        <form action="/sales/adjustSaleHistory" method="post" class="bg-light shadow p-3" novalidate>
            {{ adjustForm.hidden_tag() }}
            <div class="d-flex justify-content-between">
                <span>{{ adjustForm.sale.label}} to {{ userAction.capitalize() }} </span>
                <span>{{ adjustForm.submit(class_="btn btn-outline-danger btn-sm") }}</span>
            </div>
            <div class="table-responsive-sm">
                <table class="table table-borderless table-hover text-center">
                    <thead>
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Item</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Price w/ Tax</th>
                            <th scope="col">Price</th>
                            <th scope="col">Shipping</th>
                            <th scope="col">Packaging</th>
                            <th scope="col">Date</th>
                            <th scope="col">Profit</th>
                            {% if userAction not in ['edit', 'refund'] %}
                            <th scope="col">Refund</th>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for subfield in adjustForm.sale %}
                        <tr>
                            <td>{{ subfield }}</td>
                            <td>{{subfield.label.text["itemName"]}}</td>
                            <td>{{subfield.label.text["quantity"]}}</td>
                            <td>{{subfield.label.text["priceWithTax"]}}</td>
                            <td>{{subfield.label.text["price"]}}</td>
                            <td>{{subfield.label.text["shipping"]}}</td>
                            <td>{{subfield.label.text["packaging"]}}</td>
                            <td>{{subfield.label.text["date"]}}</td>
                            <td>{{subfield.label.text["profit"]}}</td>
                            {% if userAction not in ['edit', 'refund'] %}
                            <td>{{'X' if subfield.label.text["refund"] else ""}}</td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="d-flex flex-row justify-content-between">
                <span>
                    {% if next_url %}
                    <a class="mr-3" href="{{ next_url }}">Older Sales</a>
                    {% endif %}
                    {% if prev_url %}
                    <a href="{{ prev_url }}">Newer Sales</a>
                    {% endif %}
                </span>
            </div>
        </form>
    </div>
</div>
{% endif %}
{% endblock %}

app/templates/sales/_saleHistory.html
{% extends "sales/sales.html" %}

{% block history %}

<div class="row justify-content-around">
    <div class="col-auto bg-light shadow p-3">
        <div class="table-responsive-sm">
            <table class="table table-borderless table-hover text-center">
                <thead>
                    <tr>
                        <th scope="col">Item</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Price w/ Tax</th>
                        <th scope="col">Price</th>
                        <th scope="col">Shipping</th>
                        <th scope="col">Packaging</th>
                        <th scope="col">Date</th>
                        <th scope="col">Profit</th>
                        <th scope="col">Refund</th>
                    </tr>
                </thead>
                <tbody>
                    {% for sale in history %}
                    <tr>
                        <th scope="row">{{sale["itemName"]}}</th>
                        <td>{{sale["quantity"]}}</td>
                        <td>{{sale["priceWithTax"]}}</td>
                        <td>{{sale["price"]}}</td>
                        <td>{{sale["shipping"]}}</td>
                        <td>{{sale["packaging"]}}</td>
                        <td>{{sale["date"]}}</td>
                        <td>{{sale["profit"]}}</td>
                        <td>{{'X' if sale["refund"] else ""}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% if next_url %}
            <a class="mr-3" href="{{ next_url }}">Older Sales</a>
            {% endif %}
            {% if prev_url %}
            <a href="{{ prev_url }}">Newer Sales</a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

app/templates/sales/saleInput.html
{% extends "base.html" %}

{% block app_content %}
<div class="row justify-content-around">
    <div class="col-auto my-3">

        {% if action == "edit" %}
        <p class="text-center h4">Editing Sale For {{ form.items.data }}</p>
        {% elif action == "add" %}
        <p class="text-center h4">Add a New Sale</p>
        {% endif %}

        <form action="/sales/newSale" method="post" class="d-flex bg-light shadow p-3 my-4" novalidate>
            {{ form.hidden_tag() }}

            <div class="row">
                <div class="col-sm d-flex flex-column justify-content-between">
                    <div class="form-group">
                        {{ form.items.label }}
                        {{ form.items(class_="form-control") }}
                        {% for error in form.items.errors %}
                        <span style="color: red;">{{ '[' + error + ']' if error }}</span>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        {{ form.date.label }}
                        {{ form.date(class_="form-control") }}
                        {% for error in form.date.errors %}
                        <span style="color: red;">{{ '[' + error + ']' if error }}</span>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        {{ form.priceWithTax.label }}
                        {{ form.priceWithTax(class_="form-control") }}
                        {% for error in form.priceWithTax.errors %}
                        <span style="color: red;">{{ '[' + error + ']' if error }}</span>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        {{ form.price.label }}
                        {{ form.price(class_="form-control") }}
                        {% for error in form.price.errors %}
                        <span style="color: red;">{{ '[' + error + ']' if error }}</span>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        {{ form.quantity.label }}
                        {{ form.quantity(class_="form-control") }}
                        {% for error in form.quantity.errors %}
                        <span style="color: red;">{{ '[' + error + ']' if error }}</span>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-sm d-flex flex-column justify-content-between">
                    <div class="form-group">
                        {{ form.shipping.label }}
                        {{ form.shipping(class_="form-control") }}
                        {% for error in form.shipping.errors %}
                        <span style="color: red;">{{ '[' + error + ']' if error }}</span>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        {{ form.packaging.label }}
                        {{ form.packaging(class_="form-control") }}
                        {% for error in form.packaging.errors %}
                        <span style="color: red;">{{ '[' + error + ']' if error }}</span>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        {{ form.eBayPercent.label }}
                        {{ form.eBayPercent(class_="form-control") }}
                        {% for error in form.eBayPercent.errors %}
                        <span style="color: red;">{{ '[' + error + ']' if error }}</span>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        {{ form.payPalFixed.label }}
                        {{ form.payPalFixed(class_="form-control") }}
                        {% for error in form.payPalFixed.errors %}
                        <span style="color: red;">{{ '[' + error + ']' if error }}</span>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        {{ form.payPalPercent.label }}
                        {{ form.payPalPercent(class_="form-control") }}
                        {% for error in form.payPalPercent.errors %}
                        <span style="color: red;">{{ '[' + error + ']' if error }}</span>
                        {% endfor %}
                    </div>

                    <div class="text-right">
                        <a class="mr-3 text-secondary" href="{{ url_for('sales.sales') }}">Cancel</a>
                        {{ form.submit(class_="btn btn-outline-primary btn-sm") }}
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

app/templates/sales/sales.html
{% extends "base.html" %}

{% block app_content %}
<div class="row justify-content-around mb-3">
    <div class="col-auto d-flex flex-column justify-content-center">

        {% if zeroItems %}

        <a class="text-center h5 my-3" href="{{ url_for('items.addItem') }}">Add an item first to get started adding
            sales.</a>

        {% else %}

        <a class="text-center h5 my-3" href="{{ url_for('sales.newSale') }}"><i class="fas fa-plus"></i>&nbsp&nbspAdd a
            new sale.</a>

        {% endif %}

        {% if not zeroSales %}

        <form action="/sales/sales" method="post" class="bg-light shadow p-4 my-3" novalidate>
            {{ form.hidden_tag() }}
            <div class="row">
                <div class="col-sm-auto">
                    <div class="form-group">
                        {{ form.items.label }}
                        {{ form.items(class_="form-control") }}
                        {% for error in form.items.errors %}
                        <span style="color: red;">{{ '[' + error + ']' if error }}</span>
                        {% endfor %}
                    </div>
                    <a href="{{ url_for('sales.downloadCSV') }}"><small>Download CSV of All Sales</small></a>
                </div>
                <div class="col-sm-auto">
                    <div class="form-group">
                        {{ form.action.label }}
                        {% for subfield in form.action %}
                        <div class="form-check">
                            {{ subfield }}
                            {{ subfield.label.__call__(class_="form-check-label") }}
                        </div>
                        {% endfor %}
                        {% for error in form.action.errors %}
                        <span style="color: red;">{{ '[' + error + ']' if error }}</span>
                        {% endfor %}
                    </div>
                    <div class="text-right">{{ form.submit(class_="btn btn-outline-primary btn-sm") }}</div>
                </div>
            </div>
        </form>
    </div>
</div>

    {% block history %}{% endblock %}

    {% endif %}

{% endblock %}